### ISSUE TITLE
Unexpected extra margins are created

### ISSUE THREAD

**Issue by ghost** [plfjohnson/devEMF#3]
I want to output only the plot area graphs in an emf file.
However, it will always create unexpected extra margins.
For example, I ran the following code.

```
require(ggplot2)
require(cowplot)
require(devEMF)

df = data.frame(x=0:10, y=(0:10)^2)

emf(file="test.emf", bg="transparent", width=5, height=5, units="in", coordDPI=300)

gg = ggplot(df, aes(x=x, y=y))
gg = gg +
  geom_line(linewidth=2) +
  theme_nothing() + 
  scale_x_continuous(expand=c(0,0), limits=c(0, 10)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, 100)) +
  labs(x = NULL, y = NULL)

plot(gg)
dev.off()
```
I expected the emf file to output 5 *300 = 1500 pixels.
But in reality, an extra margin of 1 pixel was also created, resulting in a 1501 * 1501 image being output.
The margins are also visible on the PowerPoint.
This is completely unnecessary, as no graph will be drawn in that margin area.

I tried other widths and DPIs but the same (or a few pixel) margins were created.

Do you know of any solution or bug for this?

- R version 4.3.0
- RStudio 2023.03.1 Build 446
- Package ggplot2 version 3.4.2
- Package cowplot version 1.1.1
- Package devEMF version 4.3-1

**Comment by plfjohnson** [comment]
The EMF spec does not explicitly specify dimensions using pixels (although it does have a discrete coordinate system, which might be what you're referencing).  Can you upload a screenshot illustrating the issue?  Also please report the viewing program & version (e.g., powerpoint xxxx).

**Comment by ghost** [comment]
Thank you for your response.

I have prepared screenshots taken on the PowerPoint (I have framed the graphs for visualization).
The first one is a general view (fig. 1) and the second one is an enlarged view (fig. 2).
The margins I have mentioned appear on the right and bottom edges of the figures.
In the second figure, can you see the margin between the red line on the graph and the black line in the frame?

The pixel counts are from checking with Microsoft Paint (fig. 3).
Well, Microsoft Paint is not the appropriate application to open emf files...

- Microsoft® PowerPoint® for Microsoft 365 MSO (version 2304 build 16.0.16327.20200) 64-bit
I can't immediately confirm the detailed version, but I have seen the same issue with Power Point 2016 at work.

- Microsoft Paint 11.2302.18.0

![fig1](https://github.com/plfjohnson/devEMF/assets/75362403/cf59a363-1294-457c-99b7-05de69b412f8)
![fig2](https://github.com/plfjohnson/devEMF/assets/75362403/9ee81075-fcd8-4db5-be18-0e9ec63e0b3e)
![fig3](https://github.com/plfjohnson/devEMF/assets/75362403/4ddf6d45-6309-4aca-9abc-b280080dd7d3)

**Comment by plfjohnson** [comment]
Thanks; the screenshots were quite helpful.

Part of the problem arises from an inherent EMF/EMF+ discrepancy in measurement unit precision: logical bounds are specified in integer units of mm, but the graphic frame bounds are specified in integer units of 0.01mm.  Depending on unit conversion, this difference in precision creates a small gap at the right and bottom edges of the graphic.  I have pushed a change to the devEMF code that uses rounding instead of truncation to reduce this problem.

However, even after solving the above problem, I discovered that Microsoft Office adds an additional thin border that other viewing programs do not.  My solution to this gap is to leverage the difference in precision by specifying dimensions slightly smaller than the integer mm to which it will be rounded.

With devEMF currently on github, if you want to make a graphic full-bleed with no gap at all in Powerpoint, specify figure width and height in **integer** units of mm and then shrink the bounds by an additional 0.04mm.  Applying this change to your test code above:
```
emf(file="test.emf", bg="transparent", width=127-0.04, height=127-0.04, units="mm", coordDPI=300)
```

Please verify and confirm that the problem is gone with the github version of devEMF combined with these changes to figure width and height.

**Comment by ghost** [comment]
Thank you for your prompt update!
I report that the margins I mentioned are gone with your presented code.

I downloaded devEMF ver. 4.4 and re-ran the code with the size of the image presented.
As a result, I was able to create a figure on PowerPoint and Paint with no margins on the right and bottom edges.
There appears to be no problem with enlarging and reducing the image after pasting onto PowerPoint (obviously).

In the meantime, I report that when I try other sizes, the margins are sometimes there and sometimes not there (see table).
If you make further modifications in the future, I would appreciate your reference.

Anyway, this problem has been solved for my practical use, as I can output images without problems if I am careful about the output size on my code.
Again, thank you very much for your time ; )



|width|height|units|coordDPI|has_margin|
----|----|----|----|----
|default|default|default|default|False (no margin)
|127-0.04|127-0.04|mm|300|False
|127-0.01|127-0.01|mm|300|False
|127|127|mm|300|True (has margin, 1 pixel)
|7|7|cm|300|False
|7|6|cm|300|False
|10|10|cm|300|True (1 pixel)
|10-0.001|10-0.001|cm|300|False
|7|7|in|300|False (Same as default of course)
|6|6|in|300|True (6 pixels)
|5|5|in|300|True (1 pixel)

**Comment by plfjohnson** [comment]
Glad this solved your problem.  As you found, sometimes there is no gap even when margins are specified in inches or less than 0.04mm is subtracted.  But I found inconsistent results unless I subtracted 0.04.

I made a few more commits since the version you downloaded; the official v4.4 is released and on cran now (I suggest switching to the release version when you have a chance).
