### ISSUE TITLE
Word pdf with missing content

### ISSUE THREAD

**Issue by lz1nwm** [plfjohnson/devEMF#4]
There is some regression with `v4.4`. When word exports pdf the file loses some of the layers. It was fixed in `v4.1-1`.

This is the code that I'm running with `v4.3-1` and `v4.4`:
```r
library(devEMF)
library(ggplot2)

gg <- ggplot(cars, aes(x = dist, y = speed))+
    geom_line()
gg

emf(file = 'cars.emf', emfPlus = T)
print(gg)
dev.off()
```

And this is the generated pdf with the two charts (the left one is created with `v4.3-1`, the right one with `v4.4`):
![image](https://github.com/plfjohnson/devEMF/assets/10129222/2886cb24-5c8d-4a5c-96c7-f9742a2221ec)

**Comment by plfjohnson** [comment]
Thank you for reporting and giving a clear test case.

Word seems to use a different renderer when exporting to PDF relative to showing on screen, and looks like it does not react well to using physical units ("inch") as the page transform instead of virtual device units ("pixel").  I previously made the page transform change as part of a general coordinate cleanup, but just committed a new version (```v4.4-1```) that reverts the page transform.

**Comment by lz1nwm** [comment]
Thank you @plfjohnson , it works great now.
