### ISSUE TITLE
multiple pages not available for EMF device

### ISSUE THREAD

**Issue by andrewjyee** [plfjohnson/devEMF#7]
This has to do with creating Kaplan-Meier curves using the ```survminer``` package.

With the following code:

```
library('devEMF')
library('survival')
library('survminer')

for.plot <- data.frame(Duration=c(1,2,3), status=c(0,1,0))
answer <- survfit(Surv(for.plot$Duration, for.plot$status==1) ~1, data=for.plot )
the.plot <- ggsurvplot(answer, risk.table = "nrisk_cumcensor")

emf('test.emf')
print(the.plot)
dev.off()
```

I get the following error message;

```
Warning message:
  In grid::grid.newpage() : Multiple pages not available for EMF device
```

It turns out that the emf file that is generated can be used in Powerpoint without an issue.  Is there a way to avoid this error message?

**Comment by plfjohnson** [comment]
The ggsurvplot command is requesting an extra blank page.  You can see the extra page if you switch to a pdf graphics device: change the line `emf('test.emf')` to be `pdf('test.pdf')` and you'll see the output file contains two pages.

Unlike the PDF format, the EMF format does not allow for multiple pages.  The devEMF solution is to issue a warning (as you saw) and draw the contents of the pages on top of each other.  In your case, since one page is blank, drawing the two pages on top of each other gives the results you want.  If you wish to suppress the warning message, you can wrap the call as follows:
```
suppressWarnings(print(the.plot))
```

**Comment by andrewjyee** [comment]
Thank you this is very helpful to know!
